# Generated by Django 4.2.11 on 2024-07-22 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_income'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalsum',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Income',
        ),
    ]
